import React, { useState, useMemo } from 'react';
import { 
  X, 
  UserPlus, 
  Building, 
  DollarSign, 
  Shield, 
  CreditCard, 
  Check, 
  ChevronDown, 
  MapPin, 
  Plus, 
  Edit3, 
  ShieldCheck,
  Building2,
  Users,
  Sparkles,
  RotateCcw,
  Landmark,
  Mail
} from 'lucide-react';
import { Employee, EmploymentType, DirectDepositStatus } from '../types/payroll';
import { generateNextEmployeeCode } from '../utils/payrollCalculator';

export interface PresetClientPost {
  clientCode: string;
  clientName: string;
  locationArea?: string;
}

export const PRESET_CLIENT_POSTS: PresetClientPost[] = [
  { clientCode: '00001', clientName: 'FOPM - The Parkside Villas', locationArea: 'Newport City, Pasay' },
  { clientCode: '00002', clientName: 'Megaworld Newport City', locationArea: 'Pasay City' },
  { clientCode: '00003', clientName: 'Rockwell Center Towers', locationArea: 'Makati City' },
  { clientCode: '00004', clientName: 'BGC High Street Corporate', locationArea: 'Bonifacio Global City, Taguig' },
  { clientCode: '00005', clientName: 'FOPM - Two Central Salcedo', locationArea: 'Salcedo Village, Makati' },
  { clientCode: '00006', clientName: 'FOPM - Three Central Makati', locationArea: 'Valero St., Makati' },
  { clientCode: '00007', clientName: 'FOPM - Paseo Heights Salcedo', locationArea: 'Makati City' },
  { clientCode: '00008', clientName: 'FOPM - One Eastwood Avenue', locationArea: 'Eastwood City, Quezon City' },
  { clientCode: '00009', clientName: 'Ayala Land Premier - Park Terraces', locationArea: 'Ayala Center, Makati' },
  { clientCode: '00010', clientName: 'Robinsons Galleria Corporate Center', locationArea: 'Ortigas Center, Pasig' },
];

interface EmployeeModalProps {
  employeeToEdit?: Employee | null;
  existingEmployees?: Employee[];
  defaultClientCode?: string;
  onSave: (employee: Partial<Employee>) => void;
  onClose: () => void;
}

export const EmployeeModal: React.FC<EmployeeModalProps> = ({
  employeeToEdit,
  existingEmployees = [],
  defaultClientCode,
  onSave,
  onClose,
}) => {
  const isEditing = !!employeeToEdit;

  // Build unified list of posts combining presets and active employee posts
  const availablePosts = useMemo(() => {
    const map = new Map<string, { clientCode: string; clientName: string; guardCount: number; locationArea?: string }>();

    // 1. Seed presets
    PRESET_CLIENT_POSTS.forEach((p) => {
      map.set(p.clientCode, {
        clientCode: p.clientCode,
        clientName: p.clientName,
        guardCount: 0,
        locationArea: p.locationArea,
      });
    });

    // 2. Merge from current employee roster with counts
    existingEmployees.forEach((emp) => {
      if (emp.clientCode) {
        const existing = map.get(emp.clientCode);
        if (existing) {
          existing.guardCount += 1;
          if (emp.clientName && (!existing.clientName || existing.clientName.startsWith('Post '))) {
            existing.clientName = emp.clientName;
          }
        } else {
          map.set(emp.clientCode, {
            clientCode: emp.clientCode,
            clientName: emp.clientName || `Post ${emp.clientCode}`,
            guardCount: 1,
            locationArea: 'Client Detachment',
          });
        }
      }
    });

    return Array.from(map.values()).sort((a, b) => a.clientCode.localeCompare(b.clientCode));
  }, [existingEmployees]);

  // Initial client code resolution
  const initialCode = employeeToEdit?.clientCode || defaultClientCode || '00001';
  const initialPost = availablePosts.find((p) => p.clientCode === initialCode);

  const autoGeneratedCode = useMemo(() => {
    return generateNextEmployeeCode(existingEmployees);
  }, [existingEmployees]);

  const [name, setName] = useState(employeeToEdit?.name || '');
  const [employeeCode, setEmployeeCode] = useState(
    employeeToEdit?.employeeCode || autoGeneratedCode
  );
  const [email, setEmail] = useState(employeeToEdit?.email || '');
  const [role, setRole] = useState(employeeToEdit?.role || 'Security Officer');
  const [department, setDepartment] = useState(employeeToEdit?.department || 'Post Security & Access Control');
  
  // Client / Post selection state
  const [clientCode, setClientCode] = useState(initialCode);
  const [clientName, setClientName] = useState(
    employeeToEdit?.clientName || initialPost?.clientName || 'FOPM - The Parkside Villas'
  );
  const [isCustomMode, setIsCustomMode] = useState<boolean>(
    !availablePosts.some((p) => p.clientCode === initialCode)
  );

  const [dailyRate, setDailyRate] = useState<number>(employeeToEdit?.dailyRate || 695.0);
  const [employmentType, setEmploymentType] = useState<EmploymentType>(employeeToEdit?.employmentType || 'Regular');
  const [bankName, setBankName] = useState(employeeToEdit?.bankName || 'BDO Unibank');
  const [accountNumberMask, setAccountNumberMask] = useState(employeeToEdit?.accountNumberMask || '•••• 5521');

  // Statutory numbers state (SSS, PhilHealth, BIR / TIN, Pag-IBIG)
  const [sssNumber, setSssNumber] = useState(employeeToEdit?.sssNumber || '');
  const [philhealthNumber, setPhilhealthNumber] = useState(employeeToEdit?.philhealthNumber || '');
  const [tinNumber, setTinNumber] = useState(employeeToEdit?.tinNumber || '');
  const [pagibigNumber, setPagibigNumber] = useState(employeeToEdit?.pagibigNumber || '');

  // Quick generator for testing statutory compliance numbers
  const handleAutoFillSampleStatutory = () => {
    const randomDigits = (len: number) => Array.from({ length: len }, () => Math.floor(Math.random() * 10)).join('');
    setSssNumber(`34-${randomDigits(7)}-${randomDigits(1)}`);
    setPhilhealthNumber(`12-${randomDigits(9)}-${randomDigits(1)}`);
    setTinNumber(`${randomDigits(3)}-${randomDigits(3)}-${randomDigits(3)}-000`);
    setPagibigNumber(`${randomDigits(4)}-${randomDigits(4)}-${randomDigits(4)}`);
  };

  // Handle dropdown change
  const handleDropdownSelect = (value: string) => {
    if (value === 'CUSTOM') {
      setIsCustomMode(true);
      // If code was one of the presets, clear it to allow fresh input
      if (availablePosts.some((p) => p.clientCode === clientCode)) {
        const nextCodeNum = String(availablePosts.length + 1).padStart(5, '0');
        setClientCode(nextCodeNum);
        setClientName('');
      }
    } else {
      setIsCustomMode(false);
      const selected = availablePosts.find((p) => p.clientCode === value);
      if (selected) {
        setClientCode(selected.clientCode);
        setClientName(selected.clientName);
      }
    }
  };

  const selectedPostInfo = availablePosts.find((p) => p.clientCode === clientCode);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;

    onSave({
      name,
      employeeCode,
      email: email.trim() || `${name.toLowerCase().replace(/[^a-z]/g, '')}@merzagency.com`,
      role,
      department,
      clientCode: clientCode || '00001',
      clientName: clientName || 'FOPM - The Parkside Villas',
      dailyRate,
      employmentType,
      bankName,
      accountNumberMask,
      sssNumber: sssNumber.trim(),
      philhealthNumber: philhealthNumber.trim(),
      tinNumber: tinNumber.trim(),
      pagibigNumber: pagibigNumber.trim(),
      directDepositStatus: 'Verified',
    });
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-xs p-4 overflow-y-auto">
      <div className="w-full max-w-2xl bg-white rounded-2xl shadow-2xl border border-slate-200 overflow-hidden my-6">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 bg-slate-900 text-white">
          <div className="flex items-center gap-2.5">
            <div className={`p-2 rounded-lg ${isEditing ? 'bg-emerald-500/30 text-emerald-300 ring-1 ring-emerald-400/40' : 'bg-emerald-500/20 text-emerald-400'}`}>
              {isEditing ? <Edit3 className="w-5 h-5" /> : <UserPlus className="w-5 h-5" />}
            </div>
            <div>
              <h3 className="text-base font-bold">
                {isEditing ? `Edit Guard Profile: ${employeeToEdit?.name}` : 'Deploy New Security Personnel'}
              </h3>
              <p className="text-xs text-slate-400">
                {isEditing 
                  ? 'Update post assignment, wage rate, DOLE statutory IDs, and disbursement info'
                  : 'MERZ Security Solutions Agency Inc. • Post Detachment & Statutory Roster'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-4 max-h-[85vh] overflow-y-auto text-xs">
          {/* Client & Post Assignment (Prominent Deployment Selection) */}
          <div className="space-y-3 bg-emerald-50/50 border border-emerald-200/80 rounded-xl p-4">
            <div className="flex items-center justify-between">
              <h4 className="font-bold text-slate-900 uppercase tracking-wider flex items-center gap-1.5 text-[11px]">
                <ShieldCheck className="w-4 h-4 text-emerald-600" />
                Client Post Assignment & Location Deployment *
              </h4>
              <button
                type="button"
                onClick={() => setIsCustomMode(!isCustomMode)}
                className="text-[11px] font-semibold text-emerald-800 hover:text-emerald-950 underline flex items-center gap-1 cursor-pointer"
              >
                <Edit3 className="w-3 h-3" />
                <span>{isCustomMode ? 'Use Dropdown List' : 'Custom / Unlisted Post'}</span>
              </button>
            </div>

            {/* Dropdown Menu for selecting client/post location */}
            {!isCustomMode ? (
              <div className="space-y-2">
                <label className="text-slate-700 font-semibold block text-xs">
                  Select Client / Post Location
                </label>
                <div className="relative">
                  <div className="absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none text-emerald-600">
                    <Building className="w-4 h-4" />
                  </div>
                  <select
                    value={availablePosts.some((p) => p.clientCode === clientCode) ? clientCode : 'CUSTOM'}
                    onChange={(e) => handleDropdownSelect(e.target.value)}
                    className="w-full pl-9 pr-8 py-2.5 bg-white border-2 border-emerald-500/80 hover:border-emerald-600 rounded-xl text-xs font-semibold text-slate-900 focus:outline-hidden focus:ring-2 focus:ring-emerald-500 shadow-xs cursor-pointer appearance-none"
                  >
                    <optgroup label="Active Client Posts & Detachments">
                      {availablePosts.map((post) => (
                        <option key={post.clientCode} value={post.clientCode}>
                          [{post.clientCode}] {post.clientName}
                          {post.guardCount > 0 ? ` (${post.guardCount} guards currently deployed)` : ''}
                        </option>
                      ))}
                    </optgroup>
                    <optgroup label="Other Options">
                      <option value="CUSTOM">➕ + Enter New / Custom Client Post Location...</option>
                    </optgroup>
                  </select>
                  <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-slate-500">
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </div>

                {/* Selected Post Summary Callout Card */}
                {selectedPostInfo && (
                  <div className="p-2.5 bg-white rounded-lg border border-emerald-200/90 flex items-center justify-between text-xs shadow-2xs">
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-[11px] font-bold px-2 py-0.5 rounded bg-emerald-100 text-emerald-900 border border-emerald-200">
                        Post {selectedPostInfo.clientCode}
                      </span>
                      <div>
                        <span className="font-bold text-slate-900">{selectedPostInfo.clientName}</span>
                        {selectedPostInfo.locationArea && (
                          <span className="text-slate-500 text-[11px] ml-1.5">• {selectedPostInfo.locationArea}</span>
                        )}
                      </div>
                    </div>
                    {selectedPostInfo.guardCount > 0 && (
                      <span className="text-[10px] text-emerald-700 font-semibold flex items-center gap-1 bg-emerald-50 px-2 py-0.5 rounded">
                        <Users className="w-3 h-3" />
                        {selectedPostInfo.guardCount} deployed
                      </span>
                    )}
                  </div>
                )}
              </div>
            ) : (
              /* Custom / Unlisted Post Form Fields */
              <div className="space-y-2 bg-white p-3 rounded-lg border border-slate-200">
                <div className="flex items-center justify-between pb-1 border-b border-slate-100">
                  <span className="text-[11px] font-bold text-slate-700 uppercase tracking-wider">
                    New / Custom Client Site Details
                  </span>
                  <button
                    type="button"
                    onClick={() => {
                      setIsCustomMode(false);
                      setClientCode('00001');
                      setClientName('FOPM - The Parkside Villas');
                    }}
                    className="text-[10px] text-slate-500 hover:text-slate-800 underline"
                  >
                    Cancel custom, choose from list
                  </button>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                  <div>
                    <label className="text-slate-700 font-medium block mb-1">Client Code *</label>
                    <input
                      type="text"
                      required
                      value={clientCode}
                      onChange={(e) => setClientCode(e.target.value)}
                      placeholder="e.g. 00011"
                      className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-mono font-bold"
                    />
                  </div>
                  <div className="sm:col-span-2">
                    <label className="text-slate-700 font-medium block mb-1">Client / Post Location Name *</label>
                    <input
                      type="text"
                      required
                      value={clientName}
                      onChange={(e) => setClientName(e.target.value)}
                      placeholder="e.g. Ayala Malls Circuit Makati"
                      className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-medium"
                    />
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Personnel Identity */}
          <div className="space-y-3 pt-2">
            <h4 className="font-bold text-slate-900 uppercase tracking-wider flex items-center gap-1.5 text-[11px]">
              <Building2 className="w-4 h-4 text-emerald-600" />
              Guard Identification
            </h4>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="text-slate-700 font-medium block mb-1">Full Legal Name (Last, First Middle) *</label>
                <input
                  type="text"
                  required
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="e.g. Trinidad, Jennise Cassandra"
                  className="w-full px-3 py-2 text-sm bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-medium"
                />
              </div>

              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="text-slate-700 font-medium block">Employee Number (Agency Code) *</label>
                  {!isEditing && (
                    <button
                      type="button"
                      onClick={() => setEmployeeCode(autoGeneratedCode)}
                      className="text-[10px] text-emerald-700 hover:text-emerald-900 font-semibold flex items-center gap-1 cursor-pointer"
                      title="Reset to next sequential roster code"
                    >
                      <RotateCcw className="w-2.5 h-2.5" />
                      <span>Next Seq: {autoGeneratedCode}</span>
                    </button>
                  )}
                </div>
                <div className="relative">
                  <input
                    type="text"
                    required
                    value={employeeCode}
                    onChange={(e) => setEmployeeCode(e.target.value)}
                    placeholder={autoGeneratedCode}
                    className="w-full px-3 py-2 text-sm bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-mono font-bold text-red-600 focus:ring-2 focus:ring-red-400 focus:border-red-400"
                  />
                  {!isEditing && employeeCode === autoGeneratedCode && (
                    <div className="absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-700 bg-emerald-100 px-1.5 py-0.5 rounded border border-emerald-200 flex items-center gap-0.5">
                        <Sparkles className="w-2.5 h-2.5" />
                        Auto
                      </span>
                    </div>
                  )}
                </div>
                <p className="text-[10px] text-slate-500 mt-1">
                  Format: <strong className="font-mono text-slate-700 font-bold">MERZ - 2608 - XXXX</strong> (auto-proceeds on last 4 digits starting from 0107).
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="text-slate-700 font-medium block mb-1">Designation / Position *</label>
                <div className="space-y-1.5">
                  <input
                    type="text"
                    required
                    value={role}
                    onChange={(e) => setRole(e.target.value)}
                    placeholder="Security Officer, Lady Guard, Shift In-Charge"
                    className="w-full px-3 py-2 text-sm bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-medium"
                  />
                  {/* Quick role pills */}
                  <div className="flex flex-wrap gap-1">
                    {['Security Officer', 'Lady Guard (LG)', 'Shift In-Charge (SIC)', 'Security Supervisor (SS)'].map((r) => (
                      <button
                        key={r}
                        type="button"
                        onClick={() => setRole(r)}
                        className={`text-[10px] px-2 py-0.5 rounded transition cursor-pointer ${
                          role === r
                            ? 'bg-slate-900 text-white font-semibold'
                            : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                        }`}
                      >
                        {r}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              <div>
                <label className="text-slate-700 font-medium block mb-1">Daily Minimum Wage Rate (₱) *</label>
                <input
                  type="number"
                  step="5"
                  required
                  value={dailyRate}
                  onChange={(e) => setDailyRate(parseFloat(e.target.value) || 0)}
                  className="w-full px-3 py-2 text-sm bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-mono font-bold text-slate-900"
                />
                {/* Quick rate pills */}
                <div className="flex items-center gap-1 mt-1.5">
                  <span className="text-[10px] text-slate-400 mr-0.5">Presets:</span>
                  {[
                    { label: '₱645 Min', val: 645 },
                    { label: '₱695 DOLE', val: 695 },
                    { label: '₱750 SIC', val: 750 },
                    { label: '₱850 Supv', val: 850 },
                  ].map((p) => (
                    <button
                      key={p.val}
                      type="button"
                      onClick={() => setDailyRate(p.val)}
                      className={`text-[10px] px-1.5 py-0.5 rounded font-mono transition cursor-pointer ${
                        dailyRate === p.val
                          ? 'bg-emerald-700 text-white font-bold'
                          : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                      }`}
                    >
                      {p.label}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Email Address */}
            <div>
              <label className="text-slate-700 font-medium block mb-1 flex items-center justify-between">
                <span className="flex items-center gap-1">
                  <Mail className="w-3.5 h-3.5 text-slate-500" />
                  Official Email Address (for Electronic Payslip Dispatch)
                </span>
                <span className="text-[10px] text-slate-400">Optional / Auto-generated if blank</span>
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="guard.name@merzagency.com"
                className="w-full px-3 py-2 text-sm bg-slate-50 border border-slate-300 rounded-lg focus:bg-white text-slate-800"
              />
            </div>
          </div>

          {/* Government & Statutory Compliance Numbers */}
          <div className="space-y-3 pt-3 border-t border-slate-200">
            <div className="flex items-center justify-between">
              <div>
                <h4 className="font-bold text-slate-900 uppercase tracking-wider flex items-center gap-1.5 text-[11px]">
                  <Landmark className="w-4 h-4 text-emerald-600" />
                  Government Statutory Numbers (DOLE Compliance)
                </h4>
                <p className="text-[10px] text-slate-500 mt-0.5">
                  Mandated for SSS, PhilHealth, BIR (TIN), and Pag-IBIG remittances &amp; official payslip headers.
                </p>
              </div>
              <button
                type="button"
                onClick={handleAutoFillSampleStatutory}
                className="text-[10px] font-semibold text-emerald-800 hover:text-emerald-950 bg-emerald-50 hover:bg-emerald-100 border border-emerald-200 px-2 py-1 rounded-md flex items-center gap-1 cursor-pointer transition"
                title="Generate realistic Philippine statutory IDs for this guard"
              >
                <Sparkles className="w-2.5 h-2.5 text-emerald-600" />
                <span>Fill Sample IDs</span>
              </button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {/* SSS Number */}
              <div>
                <label className="text-slate-700 font-medium block mb-1 flex items-center justify-between">
                  <span className="text-xs">SSS Number</span>
                  <span className="text-[10px] text-slate-400 font-mono">10 digits</span>
                </label>
                <input
                  type="text"
                  value={sssNumber}
                  onChange={(e) => setSssNumber(e.target.value)}
                  placeholder="e.g. 34-8192031-4"
                  className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-mono font-bold text-slate-800 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                />
                <span className="text-[10px] text-slate-400 mt-0.5 block">Format: XX-XXXXXXX-X</span>
              </div>

              {/* PhilHealth Number */}
              <div>
                <label className="text-slate-700 font-medium block mb-1 flex items-center justify-between">
                  <span className="text-xs">PhilHealth ID Number</span>
                  <span className="text-[10px] text-slate-400 font-mono">12 digits</span>
                </label>
                <input
                  type="text"
                  value={philhealthNumber}
                  onChange={(e) => setPhilhealthNumber(e.target.value)}
                  placeholder="e.g. 12-054928192-1"
                  className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-mono font-bold text-slate-800 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                />
                <span className="text-[10px] text-slate-400 mt-0.5 block">Format: XX-XXXXXXXXX-X</span>
              </div>

              {/* BIR / TIN Number */}
              <div>
                <label className="text-slate-700 font-medium block mb-1 flex items-center justify-between">
                  <span className="text-xs">BIR / TIN Number</span>
                  <span className="text-[10px] text-slate-400 font-mono">9-12 digits</span>
                </label>
                <input
                  type="text"
                  value={tinNumber}
                  onChange={(e) => setTinNumber(e.target.value)}
                  placeholder="e.g. 284-918-301-000"
                  className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-mono font-bold text-slate-800 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                />
                <span className="text-[10px] text-slate-400 mt-0.5 block">Format: XXX-XXX-XXX-000</span>
              </div>

              {/* Pag-IBIG / HDMF Number */}
              <div>
                <label className="text-slate-700 font-medium block mb-1 flex items-center justify-between">
                  <span className="text-xs">Pag-IBIG / HDMF Number</span>
                  <span className="text-[10px] text-slate-400 font-mono">12 digits</span>
                </label>
                <input
                  type="text"
                  value={pagibigNumber}
                  onChange={(e) => setPagibigNumber(e.target.value)}
                  placeholder="e.g. 1210-4829-1940"
                  className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-mono font-bold text-slate-800 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                />
                <span className="text-[10px] text-slate-400 mt-0.5 block">Format: XXXX-XXXX-XXXX</span>
              </div>
            </div>
          </div>

          {/* Disbursement & Banking */}
          <div className="space-y-3 pt-3 border-t border-slate-200">
            <h4 className="font-bold text-slate-900 uppercase tracking-wider flex items-center gap-1.5 text-[11px]">
              <CreditCard className="w-4 h-4 text-emerald-600" />
              Payroll Disbursement / ATM Account
            </h4>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="text-slate-700 font-medium block mb-1">Depository Bank</label>
                <input
                  type="text"
                  value={bankName}
                  onChange={(e) => setBankName(e.target.value)}
                  placeholder="BDO Unibank, BPI, Landbank"
                  className="w-full px-3 py-2 text-sm bg-slate-50 border border-slate-300 rounded-lg focus:bg-white"
                />
                <div className="flex flex-wrap gap-1 mt-1">
                  {['BDO Unibank', 'BPI Bank', 'Landbank', 'Metrobank', 'Security Bank'].map((b) => (
                    <button
                      key={b}
                      type="button"
                      onClick={() => setBankName(b)}
                      className="text-[10px] px-1.5 py-0.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-600"
                    >
                      {b}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="text-slate-700 font-medium block mb-1">Account Mask / Last 4 Digits</label>
                <input
                  type="text"
                  value={accountNumberMask}
                  onChange={(e) => setAccountNumberMask(e.target.value)}
                  placeholder="•••• 4920"
                  className="w-full px-3 py-2 text-sm bg-slate-50 border border-slate-300 rounded-lg focus:bg-white font-mono"
                />
                <span className="text-[10px] text-slate-400 mt-1 block">
                  Status: <strong className="text-emerald-700 font-medium">Direct Deposit Verified</strong>
                </span>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="flex items-center justify-between pt-4 border-t border-slate-200">
            <div className="text-[11px] text-slate-500">
              {isEditing ? 'Assigned to:' : 'Deploying to:'}{' '}
              <strong className="text-slate-900 font-mono">[{clientCode}]</strong> {clientName}
            </div>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 text-xs font-medium text-slate-600 hover:text-slate-900 rounded-lg cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="flex items-center gap-1.5 px-5 py-2.5 text-xs font-bold bg-emerald-700 hover:bg-emerald-800 text-white rounded-lg transition shadow-xs cursor-pointer"
              >
                <Check className="w-4 h-4 text-emerald-200" />
                <span>{isEditing ? 'Save Profile Changes' : 'Deploy Guard to Post'}</span>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};

